### PR TITLE
Fix generation OS X app when not providing icon and error handling

### PR DESCRIPTION
**Pull request by VitaliyR**
https://github.com/paulmillr/loggy/pull/23

Decided to fix here. Also, fixed issue with generating an icon in OS X Application for showing notifications. Discovered running `node test.js` :)

### CODE REVIEW

**Comment by shvaikalesh** [comment]
Hey @VitaliyR, thanks for the PR. Could you please suppress errors in `index.html`?

**Comment by VitaliyR** [comment]
@shvaikalesh Hi! What does that mean? `index.js` is returning a function, but not a stream. Are you proposing to add parameters for OS handlers? Or Proxy?

**Comment by paulmillr** [comment]
9c860da

**Comment by paulmillr** [comment]
e7887fc

**Comment by VitaliyR** [comment]
Got it, thanks.

**Pull request merged**
