### PR TITLE
Absolute path is required for icon

### PR DESCRIPTION
**Pull request by shvaikalesh**

### CODE REVIEW

**Comment by paulmillr** [comment]
no need for prs — you should have an access

**Comment by shvaikalesh** [comment]
I do have access; I didn't use `path` module in example, thought you may have comments on it.

**Comment by paulmillr** [comment]
yeah I think `requiring` absolute path is not cool. can we make it relative by default or sth?

**Comment by shvaikalesh** [comment]
Sadly, no. We can `throw` and catch error, parse the stack and see from what file `notify` is called, so we can obtain the `base` for relative to absolute convertion.

**Comment by shvaikalesh** [comment]
Remember https://github.com/brunch/commonjs-require-definition/pull/28? Same shit.

**Pull request merged**
